// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vizin.Models;

#nullable disable

namespace vizin.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20260216201150_AddTotalCostToBooking")]
    partial class AddTotalCostToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status_enum", new[] { "CREATED", "CONFIRMED", "CANCELED", "FINISHED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status_enum", new[] { "PENDING", "PAID", "FAILED", "REFUNDED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_type_enum", new[] { "HOST", "GUEST", "ADMIN" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TbPropertyAmenity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid")
                        .HasColumnName("amenity_id");

                    b.HasKey("PropertyId", "AmenityId")
                        .HasName("tb_property_amenity_pkey");

                    b.HasIndex("AmenityId");

                    b.ToTable("tb_property_amenity", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tb_amenity_pkey");

                    b.HasIndex(new[] { "Name" }, "tb_amenity_name_key")
                        .IsUnique();

                    b.ToTable("tb_amenity", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CancelationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelation_date");

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkin_date");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkout_date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tb_booking_pkey");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_booking", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tb_favorite_pkey");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_favorite", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<int>("StatusPayment")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("tb_payment_pkey");

                    b.HasIndex("BookingId");

                    b.ToTable("tb_payment", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccomodationType")
                        .HasColumnType("integer")
                        .HasColumnName("accomodation_type");

                    b.Property<bool>("Availability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("availability");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("DailyValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("daily_value");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_address");

                    b.Property<int>("PropertyCategory")
                        .HasColumnType("integer")
                        .HasColumnName("property_category");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tb_property_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("tb_property", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("note");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("tb_review_pkey");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_review", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("tb_user_pkey");

                    b.HasIndex(new[] { "Email" }, "tb_user_email_key")
                        .IsUnique();

                    b.ToTable("tb_user", "sistema_locacao");
                });

            modelBuilder.Entity("vizin.Models.TbUser1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("tb_user_pkey");

                    b.HasIndex(new[] { "Email" }, "tb_user_email_key")
                        .IsUnique()
                        .HasDatabaseName("tb_user_email_key1");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("TbPropertyAmenity", b =>
                {
                    b.HasOne("vizin.Models.TbAmenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("fk_property_amenity_amenity");

                    b.HasOne("vizin.Models.TbProperty", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("fk_property_amenity_property");
                });

            modelBuilder.Entity("vizin.Models.TbBooking", b =>
                {
                    b.HasOne("vizin.Models.TbProperty", "Property")
                        .WithMany("TbBookings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_property");

                    b.HasOne("vizin.Models.TbUser", "User")
                        .WithMany("TbBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_user");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vizin.Models.TbFavorite", b =>
                {
                    b.HasOne("vizin.Models.TbProperty", "Property")
                        .WithMany("TbFavorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_property");

                    b.HasOne("vizin.Models.TbUser", "User")
                        .WithMany("TbFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_user");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vizin.Models.TbPayment", b =>
                {
                    b.HasOne("vizin.Models.TbBooking", "Booking")
                        .WithMany("TbPayments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("vizin.Models.TbProperty", b =>
                {
                    b.HasOne("vizin.Models.TbUser", "User")
                        .WithMany("TbProperties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_property_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vizin.Models.TbReview", b =>
                {
                    b.HasOne("vizin.Models.TbBooking", "Booking")
                        .WithMany("TbReviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_booking");

                    b.HasOne("vizin.Models.TbUser", "User")
                        .WithMany("TbReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_review_user");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vizin.Models.TbBooking", b =>
                {
                    b.Navigation("TbPayments");

                    b.Navigation("TbReviews");
                });

            modelBuilder.Entity("vizin.Models.TbProperty", b =>
                {
                    b.Navigation("TbBookings");

                    b.Navigation("TbFavorites");
                });

            modelBuilder.Entity("vizin.Models.TbUser", b =>
                {
                    b.Navigation("TbBookings");

                    b.Navigation("TbFavorites");

                    b.Navigation("TbProperties");

                    b.Navigation("TbReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
